
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  application.properties: |
  SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: "1234"
