name: github action CI

on: workflow_dispatch

env:
  IMAGE_NAME: cloud-sample

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Generate Version
      id: gen-version
      run: echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: ACR Login - Base ACR
      uses: azure/docker-login@v1
      with:
        login-server: cepgbaseacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME_BASE }}
        password: ${{ secrets.ACR_PASSWORD_BASE }}

    - name: Build & Tag Docker Image
      run: |
        docker build -t cepgbaseacr.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }} -f Dockerfile .
        docker tag cepgbaseacr.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ce82270864acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: ACR Login - Target ACR
      uses: azure/docker-login@v1
      with:
        login-server: ce82270864acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME_TARGET }}
        password: ${{ secrets.ACR_PASSWORD_TARGET }}

    - name: Push Image
      run: |
        docker push ce82270864acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Update Kubernetes Resources
      run: |
        cd manifests/overlays/prod
        kustomize edit set image ce82270864acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        cat kustomization.yaml

    - name: Commit and Push Updates
      run: |
        git config --global user.email "rkwhk7203@naver.com"
        git config --global user.name "haram"
        git add manifests/overlays/prod/kustomization.yaml
        git commit -m "Update image tag to ${{ env.VERSION }}" || echo "No changes to commit"
        git push origin main
