name: github action CI

on: workflow_dispatch

env:
  IMAGE_NAME: springboot-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ce82270864acr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ce82270864acr.azurecr.io/${{ env.IMAGE_NAME }}:latest .
    
    - name: Push Docker Image
      run: |
        docker push ce82270864acr.azurecr.io/${{ env.IMAGE_NAME }}:latest
